# Generated by Django 4.0.4 on 2023-01-13 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50, unique=True)),
                ('eventCreatedDate', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('userFirstName', models.CharField(blank=True, max_length=50)),
                ('userLastName', models.CharField(blank=True, max_length=50)),
                ('userMiddleName', models.CharField(blank=True, max_length=50)),
                ('userDOB', models.DateField()),
                ('userPhone', models.CharField(blank=True, max_length=10)),
                ('userAddress1', models.CharField(blank=True, max_length=50)),
                ('userAddress2', models.CharField(blank=True, max_length=50)),
                ('userAddress3', models.CharField(blank=True, max_length=50)),
                ('userPinCode', models.CharField(blank=True, max_length=6)),
                ('userAadhar', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
