# Generated by Django 4.1.3 on 2023-01-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userDOB',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
