# Generated by Django 4.1.3 on 2023-01-20 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_useraddress1_userprofile_useraddress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventtype',
            old_name='eventCreatedDate',
            new_name='CreatedDate',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='eventDescription',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='eventtype',
            old_name='eventName',
            new_name='Name',
        ),
        migrations.RemoveField(
            model_name='eventtype',
            name='eventType',
        ),
        migrations.CreateModel(
            name='eventName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=50, unique=True)),
                ('Description', models.CharField(blank=True, max_length=50, unique=True)),
                ('CreatedDate', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Typeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtype')),
            ],
        ),
    ]
