# Generated by Django 4.1.3 on 2023-01-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userperfdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userperfdata',
            name='fld_value',
            field=models.IntegerField(),
        ),
    ]
